stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/bronze/ml-1m/ratings.dat
    - src/preprocess.py
    outs:
    - data/silver/ml-1m
  negative_sampling:
    cmd: python src/negative_sampling.py
    deps:
    - data/silver/ml-1m/dataset.pkl
    - src/negative_sampling.py
    outs:
    - data/gold/ml-1m/negative_samples
  data_loading:
    cmd: python src/data_loading.py
    deps:
    - data/gold/ml-1m/negative_samples/negative_samples_val.pkl
    - data/silver/ml-1m/dataset.pkl
    - src/data_loading.py
    outs:
    - data/gold/ml-1m/dataloaders
